# Generated by Django 3.2.5 on 2022-01-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='price_paid',
            field=models.FloatField(default=0, max_length=16, null=True),
        ),
    ]
