# Generated by Django 3.2.5 on 2022-01-30 17:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0002_portfolio_price_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='amount',
            field=models.FloatField(max_length=8),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='price_paid',
            field=models.FloatField(max_length=16),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markets', to='market.market'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usernames', to='auth.user'),
        ),
    ]
